env:
  # Enable all ECMAScript 2022 globals and automatically set the ecmaVersion parser option to 13.
  es2022: true
  # Enable Browser global variables.
  browser: true
  # Enable Node.js global variables.
  node: true
  # Enable shared Browser <-> Node.js global variables.
  shared-node-browser: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react/jsx-runtime' # Use the new JSX transform from React 17+.

root: true # Stop ESLint from looking for config files in parent folders.
overrides: []
globals:
  JSX: readonly

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - '@typescript-eslint'
  - prettier
  - jsx-a11y
  - import
  - react-hooks
  - sort-keys-fix

rules:
  no-alert: warn
  no-console: warn
  no-debugger: warn
  no-dupe-keys: error
  prettier/prettier:
    - warn
    - {}
    - properties:
        usePrettierrc: true
  react/prop-types: 'off'
  react-hooks/rules-of-hooks: error
  sort-keys-fix/sort-keys-fix: warn
  import/default: error
  import/export: error
  import/named: error
  import/no-anonymous-default-export: 'off'
  import/no-duplicates: error
  import/no-named-as-default: error
  import/no-named-as-default-member: 'off'
  import/no-unresolved: error
  import/order:
    - warn
    - alphabetize:
        caseInsensitive: true
        order: asc
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
      newlines-between: never

settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
    typescript:
      alwaysTryTypes: true
      project:
        - tsconfig.json
  react:
    version: detect
